version: "3.9"
services:
  postgres:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    ports:
      - "5412:5432"
